import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { accounts, providerLabel } from "@/lib/mail-data";
import { useColors } from "@/hooks/use-colors";

export default function AccountsScreen() {
  const colors = useColors();
  return <ScreenContainer edges={["top", "left", "right", "bottom"]}>
    <View style={[styles.header, { borderBottomColor: colors.border }]}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.icon, pressed && styles.pressed]}><IconSymbol name="chevron.left" size={25} color={colors.foreground} /></Pressable><Text style={[styles.title, { color: colors.foreground }]}>Konten</Text><View style={styles.icon} /></View>
    <ScrollView contentContainerStyle={styles.content}>
      <Text style={[styles.intro, { color: colors.muted }]}>Verwalte deine verbundenen Postfächer und lege fest, über welches Konto neue Nachrichten gesendet werden.</Text>
      {accounts.map((account) => <View key={account.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.providerIcon, { backgroundColor: `${account.color}20` }]}><Text style={[styles.providerLetter, { color: account.color }]}>{account.email[0].toUpperCase()}</Text></View><View style={styles.cardText}><Text style={[styles.accountName, { color: colors.foreground }]}>{account.name}</Text><Text style={[styles.email, { color: colors.muted }]}>{account.email}</Text><View style={styles.statusRow}><View style={[styles.statusDot, { backgroundColor: account.status === "synced" ? colors.success : colors.warning }]} /><Text style={[styles.status, { color: account.status === "synced" ? colors.success : colors.warning }]}>{account.status === "synced" ? "Synchronisiert" : "Wird synchronisiert"} · {providerLabel[account.provider]}</Text></View></View><Pressable accessibilityLabel={`${account.name} Optionen`} style={({ pressed }) => [styles.more, pressed && styles.pressed]}><IconSymbol name="ellipsis" size={21} color={colors.muted} /></Pressable></View>)}
      <Pressable onPress={() => router.push("/add-account")} style={({ pressed }) => [styles.addCard, { borderColor: colors.primary }, pressed && styles.pressed]}><View style={[styles.plus, { backgroundColor: `${colors.primary}14` }]}><IconSymbol name="plus" size={22} color={colors.primary} /></View><View><Text style={[styles.addTitle, { color: colors.primary }]}>Konto hinzufügen</Text><Text style={[styles.addSubtitle, { color: colors.muted }]}>Gmail, Outlook, iCloud oder IMAP</Text></View></Pressable>
      <View style={[styles.securityNote, { backgroundColor: colors.surface }]}><IconSymbol name="lock.fill" size={18} color={colors.primary} /><Text style={[styles.securityText, { color: colors.muted }]}>Deine Zugangsdaten werden verschlüsselt und nicht als Klartext gespeichert.</Text></View>
    </ScrollView>
  </ScreenContainer>;
}
const styles = StyleSheet.create({ header: { height: 58, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16 }, icon: { width: 42, height: 42, justifyContent: "center" }, title: { fontSize: 17, fontWeight: "800" }, content: { padding: 20, paddingBottom: 40 }, intro: { fontSize: 14, lineHeight: 21, marginBottom: 20 }, card: { borderWidth: 1, borderRadius: 17, padding: 15, flexDirection: "row", alignItems: "center", marginBottom: 10 }, providerIcon: { width: 44, height: 44, borderRadius: 13, alignItems: "center", justifyContent: "center", marginRight: 12 }, providerLetter: { fontSize: 20, fontWeight: "800" }, cardText: { flex: 1 }, accountName: { fontSize: 15, fontWeight: "800" }, email: { fontSize: 12, marginTop: 3 }, statusRow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 7 }, statusDot: { width: 6, height: 6, borderRadius: 3 }, status: { fontSize: 11, fontWeight: "700" }, more: { padding: 8 }, addCard: { borderWidth: 1.5, borderStyle: "dashed", borderRadius: 17, padding: 15, flexDirection: "row", alignItems: "center", gap: 12, marginTop: 8 }, plus: { width: 44, height: 44, borderRadius: 13, alignItems: "center", justifyContent: "center" }, addTitle: { fontWeight: "800", fontSize: 15 }, addSubtitle: { fontSize: 12, marginTop: 3 }, securityNote: { flexDirection: "row", gap: 9, padding: 15, borderRadius: 14, marginTop: 24 }, securityText: { flex: 1, fontSize: 12, lineHeight: 18 }, pressed: { opacity: 0.65 } });
